### ISSUE TITLE
set a custom header through a filter?

### ISSUE THREAD

**Issue by redmar** [magneticio/vamp-router#19]
Heya, great work on vamp! I'm evaluating it and have a question: 

Is it possible to set a custom HTTP header with a filter?

If not, would you be open for the feature? And could you point me in the right direction on implementing it?

**Comment by olafmol** [comment]
Hi Redmar,

thanks for evaluating Vamp and giving your feedback, much appreciated! 

Could you give us more info on what you are trying to achieve, ie what is your use-case?

cheers!

**Comment by redmar** [comment]
Currently we're setting X-Frame-Origin settings globally on the edge (i.e. haproxy) in our current setup.

**Comment by olafmol** [comment]
Ok, so you want to use Vamp to set your HTTP header. Vamp router uses Haproxy under the hood, so you can use the same ACL definitions you are already using, ie: 

http://vamp.io/documentation/reference/routings_and_filters/

Does this help you?

**Comment by redmar** [comment]
tnx for the quick responses, i'll just try to get it to work on my dev env first.

**Comment by tnolet** [comment]
@redmar This is not a feature yet in the Vamp DSL, and there is quite a difference between setting response headers and request headers. For now, you can "hard "set a header on the response on the edge HAProxy by simple editing the template Vamp Router uses for creating the eventual Haproxy config file. If you look at https://github.com/magneticio/vamp-router/blob/master/configuration/templates/haproxy_config.template you'll see some headers we set our selves, i.e. `http-response set-header X-Vamp-Server-Name %s`

**Comment by redmar** [comment]
Thanks! was already looking for that template :-)

**Comment by tnolet** [comment]
Does this help for now?
