### ISSUE TITLE
vamp-router-0.7.9.2-1.x86_64 uses systemctl which is not available on RHEL6

### ISSUE THREAD

**Issue by metskem-rabo** [magneticio/vamp-router#21]
(This might be WorksAsDesigned, but...)
I just tried to install vamp-router-0.7.9.2-1.x86_64 : 

```
[root@lsrv5269 metskeh]# rpm -i vamp-router-0.7.9.2-1.x86_64.rpm
Creating system group: vamp-router
Creating system user: vamp-router in vamp-router with vamp-router user-daemon and shell /bin/false
/var/tmp/rpm-tmp.efZZeX: line 7: systemctl: command not found
/var/tmp/rpm-tmp.efZZeX: line 8: systemctl: command not found
vamp-router could not be registered or started
[root@lsrv5269 metskeh]# 
```

**Comment by plamola** [comment]
Ah, RHEL6 uses upstart instead of systemd (RHEL7).

So, if we want to support RHEL6 (which we probably should), we need to ship a different flavour of RPM for RHEL6.

**Comment by plamola** [comment]
@metskem-rabo Thank you for reporting this. 

I've opened an new issue for this in our Vamp repo, since it will probably also affect vamp-core & vamp-pulse.

**Comment by tnolet** [comment]
We'll pick this up ASAP. Progress will be logged in https://github.com/magneticio/vamp/issues/301
