### ISSUE TITLE
The most recent docker image '0.7.10' pegs the CPU

### ISSUE THREAD

**Issue by mmontagna** [magneticio/vamp-router#23]
I tried running the following command from the readme, 'docker run --net=host magneticio/vamp-router:latest', and while the container starts successfully. The vamp-router process uses 100% of the cpu and never stops doing so. 

Is this the expected behavior? I let it sit for quite some time, thinking it might be simple initializing things, but it still ran at 100% cpu usage. 

![screenshot from 2015-09-06 18 17 27](https://cloud.githubusercontent.com/assets/6549664/9707651/99a84aec-54c3-11e5-91dd-22c75ca9f2bd.png)
 I believe that currently the 'latest' tag is set to '0.7.10'. The behavior does not occur if I run '0.7.9'.

**Comment by tnolet** [comment]
@mmontagna I'm looking into this now. I'm affraid maybe some debugging code with relation to https://github.com/magneticio/vamp/issues/322 has made it into the release.

**Comment by tnolet** [comment]
@mmontagna I found the issue. Two stray "default:" statements in a select loop.  See here https://github.com/magneticio/vamp-router/commit/0605a2c12b547b58528f29ad4e5741c85b466baa We used them for debugging but forgot to remove them. We're building now and we'll push a new container. We'll keep the 0.7.10 version number for now. Thanks for reporting.

**Comment by mmontagna** [comment]
That was fast! Thanks for looking into it!
