### ISSUE TITLE
HAproxy logs are not visible in vamp-router.log file

### ISSUE THREAD

**Issue by seregasheypak** [magneticio/vamp-router#26]
```

 ###
 #
 # Experimental: Logging Setup
 #
 # We log to a unix socket and read that socket from the Go program
 #
 #
 log /var/run/vamp.log.sock local0
```

logs do not appear...

**Comment by olafmol** [comment]
Hi seregasheypak, thanks for reporting! What version of Vamp are you running?

**Comment by seregasheypak** [comment]
Hi!

 docker run --net=host magneticio/vamp-router:latest


2015-10-13 22:16 GMT+02:00 Olaf <notifications@github.com>:
