### ISSUE TITLE
vamp-router build error

### ISSUE THREAD

**Issue by neetusanjay** [magneticio/vamp-router#27]
Please help!!, I am getting below compilation error as part of vamp-router install on Linux RHEL 7 (3.10.0-229.el7.x86_64). 

Below are list of steps performed.

git clone https://github.com/magneticio/vamp-router 
cd vamp-router
go get
or 
# go install
# github.com/magneticio/vamp-router/api
api/backend.go:44: non-bool c.Bind(&backend) (type error) used as if condition
api/backend.go:107: non-bool c.Bind(&server) (type error) used as if condition
api/backend.go:127: non-bool c.Bind(&json) (type error) used as if condition
api/config.go:24: non-bool c.Bind(&config) (type error) used as if condition
api/frontend.go:44: non-bool c.Bind(&frontend) (type error) used as if condition
api/frontend.go:89: non-bool c.Bind(&Filter) (type error) used as if condition
api/routes.go:45: non-bool c.Bind(&route) (type error) used as if condition
api/routes.go:63: non-bool c.Bind(&route) (type error) used as if condition
api/routes.go:129: non-bool c.Bind(&service) (type error) used as if condition
api/routes.go:148: non-bool c.Bind(&services) (type error) used as if condition
api/routes.go:148: too many errors

**Comment by dragoslav** [comment]
Hi @neetusanjay, could you run `godep restore` (https://github.com/tools/godep)?

**Comment by neetusanjay** [comment]
Thank you @dragoslav!! That worked.

Steps performed: 
go get github.com/tools/godep
godep restore
go install
