### ISSUE TITLE
Vamp router fails to start with -configPath and -binary

### ISSUE THREAD

**Issue by neetusanjay** [magneticio/vamp-router#28]
Please help!!...I am not able to start vamp-router with -binary and -configPath parameters. 

Command used:
docker run --net=host magneticio/vamp-router:latest -binary="/usr/sbin/haproxy" -configPath="/etc/haproxy/haproxy.cfg"

Error:
[root@scsblnx-400003 ~]# docker run --net=host magneticio/vamp-router:latest -binary="/usr/sbin/haproxy" -configPath="/etc/haproxy/haproxy.cfg"
14:50:23.063 main INFO ==>
██╗   ██╗ █████╗ ███╗   ███╗██████╗
██║   ██║██╔══██╗████╗ ████║██╔══██╗
██║   ██║███████║██╔████╔██║██████╔╝
╚██╗ ██╔╝██╔══██║██║╚██╔╝██║██╔═══╝
 ╚████╔╝ ██║  ██║██║ ╚═╝ ██║██║
  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
                       router
                       version 0.7.10
                       by magnetic.io

14:50:23.064 main NOTI ==>  Attempting to load config at /etc/haproxy/haproxy.cfg
14:50:23.064 main NOTI ==>  Did not find a config...initializing empty config
14:50:23.064 main CRIT ==>  Could not render initial config, exiting...

HA Proxy config file path
# ls -lrt /etc/haproxy/haproxy.cfg
-rwxrwxrwx 1 root root 3142 Sep  4  2014 /etc/haproxy/haproxy.cfg

HA Proxy binary path

# ls -lrta /usr/sbin/haproxy
-rwxrwxrwx 1 root root 800624 Sep  4  2014 /usr/sbin/haproxy

My OS version : Linux RHEL 7 (3.10.0-229.el7.x86_64)

Thank you in advance
Sanjay

**Comment by dragoslav** [comment]
Hi @neetusanjay, `-configPath` is path to `vamp_router.json` file (example https://github.com/magneticio/vamp-router/blob/master/examples/example1.json), not to HAProxy configuration. It makes more sense to run vamp-router with that argument outside of docker container.

**Comment by neetusanjay** [comment]
Thank you for quick response.
