### ISSUE TITLE
Is there a way to configure an ssl cert for a frontend?

### ISSUE THREAD

**Issue by cinterloper** [magneticio/vamp-router#29]
Is there a way to configure an ssl cert for a frontend?

**Comment by dragoslav** [comment]
You could update the template: configuration/templates/haproxy_config.template
For instance `bind {{.BindIp}}:{{.BindPort}} ssl crt /path/to/pem`

**Comment by cinterloper** [comment]
i see, but not in the REST api. 
thanks for the info, if i implement this, ill send a pr
