### ISSUE TITLE
Golang Version

### ISSUE THREAD

**Issue by densone** [magneticio/vamp-router#30]
Hey There, 
Wondering if this has been tested on golang 1.5.  I am getting some interesting build errors. Any build instructions? Maybe I am making a mistake?

**Comment by densone** [comment]
api/backend.go:44: non-bool c.Bind(&backend) (type error) used as if condition

**Comment by dragoslav** [comment]
hi @densone could you check #27?

**Comment by densone** [comment]
thanks. Assuming it's pinned to an older version of gin.
