### ISSUE TITLE
# in Json tripped me up

### ISSUE THREAD

**Issue by densone** [magneticio/vamp-router#31]
I've been testing vamp-router, and was copying and pasting examples from the readme.  
There are lots of hashes in the json examples so anyone that just copies and pastes, that son will not parse. I also would only get the bad request error back and nothing helpful was dumped into the log so I had to dump c.Errors to figure out it was the parsing error. I'm happy to fix this if you guys are ok with me removing the hashes and submitting a PR.

**Comment by olafmol** [comment]
Hi Sean, thanks for notifying! We'd be happy to update the examples. After internal discussion i'd like to propose that we provide better explanation so people directly see what can be pasted and what needs to be removed as it is a comment to explain. Is that something you could live with?

**Comment by densone** [comment]
Sounds good Olaf.

**Comment by avinash-katiyar** [comment]
i am not able to post a single request despite rest client APIs are up. It always says bad request 400
