### ISSUE TITLE
Potential bug with c.Bind?

### ISSUE THREAD

**Issue by densone** [magneticio/vamp-router#32]
Trying to create a "backend" I continue to get an error over and over. So, I added some debug logging c.Errors shows me the error "ProxyMode required". My json clearly has proxyMode set, but I still receive the error. If I remove the "required" binding, it works and proxyMode gets set. I am stumped by this one. Can only guess it might be a bug in gin? 

Here's the json  

``` json

        {
            "name" : "syn-aef101",
            "mode" : "http",
            "servers" : [
                {
                    "name" : "synaef0010",
                    "host" : "192.168.59.103",
                    "port" : 8081,
                    "weight" : 100,
                    "maxconn" : 1000,
                    "check" : true,
                    "checkInterval" : 10
                    },
                {
                    "name" : "synaef0011",
                    "host" : "192.168.59.103",
                    "port" : 8082,
                    "weight" : 100,
                    "maxconn" : 1000,
                    "check" : true,
                    "checkInterval" : 10
                }
            ],
            "proxyMode" : false
        }


```

**Comment by olafmol** [comment]
Hi Sean, thanks for reporting, we will take a look! FYI: at this moment Vamp Router is not actively developed, as we iterated to Vamp Gateway Agent (https://github.com/magneticio/vamp-gateway-agent) which is better suited for high-available (HA) production-grade setups. You can use the Vamp (core) to control Vamp Gateway Agent settings using Vamp's REST API .

**Comment by dragoslav** [comment]
Of course pull requests are welcome.

**Comment by achautha** [comment]
Can we use vamp-gateway-agent as an independent component like vamp-router ?  To be precise, Do I need other vamp components to install and use vamp-gateway-agent ?

**Comment by densone** [comment]
Oh bummer .. I actually rewrote pieces vamp router for ha with zookeeper using the locking mechanism .. Works really well ..  I removed all of the reads from disk for the Json config , added save functions , support to avoid deadlocks with zk.. Either way, good work

**Comment by dragoslav** [comment]
@achautha yes, VGA can be used without any other Vamp component. The newest version can also read HAProxy configuration from etcd and Consul. Advantage of Vamp Router is RESTful interface to configure HAProxy, while VGA takes the already generated HAProxy configuration. One of VGA use cases is "synchronization" of the same configuration across multiple HAProxy instances.

**Comment by olafmol** [comment]
@densone sounds interesting what you've done. Is there a way for your to do a pull-request so we can merge your additions/improvements into Vamp Router?
