### ISSUE TITLE
The docker image is not consistent with the Dockerfile in the git repository

### ISSUE THREAD

**Issue by mpaluru** [magneticio/vamp-router#33]
**Dockerfile from the image on docker hub:**
MAINTAINER Tim Nolet tnolet@magnetic.io
WORKDIR /opt/docker
ADD dir:985a50ce70482f89bdc2087e1a2f52face7c83ee3e479d932f539b49d17cc7a2 in /opt
USER root
ENTRYPOINT &{["/opt/docker/vamp-router"]}
CMD []
RUN echo 'deb http://ppa.launchpad.net/vbernat/haproxy-1.5/ubuntu trusty main' >> /etc/apt/sources.list
RUN /opt/docker/vamp-router
RUN /opt/docker/data

**This is totally different from:**
MAINTAINER tim@magnetic.io
ADD ./target/linux_i386/vamp-router /vamp-router
ADD ./configuration /configuration
ADD ./examples /examples
ADD ./target/linux_i386/haproxy /usr/sbin/haproxy
EXPOSE 80
EXPOSE 10001
EXPOSE 1988
ENTRYPOINT ["/vamp-router"]

**Comment by olafmol** [comment]
Hi @mpaluru thanks for reporting. Vamp Router is currently not actively maintained, as it's not designed for running in High-available setups. For this we created the Vamp Gateway Agent project, which can be setup in HA clusters. In the future we might pick up Vamp Router again if enough interest. Could you tell us more about your specific use-case for Vamp Router?
