### ISSUE TITLE
State of this code?

### ISSUE THREAD

**Issue by faddat** [magneticio/vamp-router#34]
We're giving serious thought to using this as our primary routing tool.  

See:
https://github.com/Klouds/kDaemon/issues/7

Basically we are going to run multi-monoliths with it-- not microservices.  Do you have any red flags or does this sound tenable to you?

**Comment by olafmol** [comment]
To give a good answer i would need to better understand your requirements and use-case. Like to setup a (skype/hangouts) call to discuss this, this works best.

**Comment by faddat** [comment]
Hey, I'd like that too!

Sorry, I missed your message.  faddat@gmail.com on hangouts, please :).
