### ISSUE TITLE
Docker Swarm Not Working

### ISSUE THREAD

**Issue by mastermindg** [magneticio/vamp-router#35]
The code is 2 years old which pre-dates swarm so it's not a big surprise that it doesn't work with swarm...but it doesn't. I'm running Docker 1.13.1 and vamp-router works great standalone with published ports but when I launch it as a service with published ports I can't connect to the container. There are no errors in the container or hosts' logs.

**Comment by olafmol** [comment]
Hi @mastermindg Vamp-router is indeed deprecated (NOTE: Since version 0.8.0, Vamp-router is not used in common Vamp setup.) Is there a specific use-case you can describe that you're looking for in Vamp Router that "full Vamp" cannot provide you? tnx!

**Comment by mastermindg** [comment]
I suspected there was a larger component here. Vamp is exactly what I'm looking for! I'm go full Vanp and work off of that repo. Thanks!

**Comment by olafmol** [comment]
Hi @mastermindg we have full docker swarm support in the pipeline for the near future. Currently Vamp is tested best against DC/OS and Kubernetes. Let us know if we can help somewhere.
